In [ ]:
#Maths/Stat Methods
#Boolean Array Operations
#Sorting/Unique Values

In [1]:
import numpy as np

#Math/Stat Method
list1 = [1, 1.1, -9, 45]
arr1 = np.array(list1)

list2 = [[1.1,2.3, -98, 54], [-0.9, 0.33, 10, 12]]
arr2 = np.array(list2)

In [2]:
#arrays have many built-in functions that aggregate the data
arr1.mean()

np.float64(9.525)

In [3]:
print(arr2.mean())
print(arr2.mean(0))
print(arr2.mean(1))

-2.39625
[  0.1     1.315 -44.     33.   ]
[-10.15     5.3575]


In [4]:
np.mean(arr2)

np.float64(-2.39625)

In [5]:
arr2.cumsum(0)

array([[  1.1 ,   2.3 , -98.  ,  54.  ],
       [  0.2 ,   2.63, -88.  ,  66.  ]])

In [6]:
arr2

array([[  1.1 ,   2.3 , -98.  ,  54.  ],
       [ -0.9 ,   0.33,  10.  ,  12.  ]])

In [7]:
#Boolean Array operations
mask = (arr1>0)
mask

array([ True,  True, False,  True])

In [8]:
mask.sum()

np.int64(3)

In [9]:
mask.any()

np.True_

In [10]:
mask.all()

np.False_

In [11]:
#Sorting/Unique Values
arr1

array([ 1. ,  1.1, -9. , 45. ])

In [13]:
#sort an array in place
arr1.sort()
arr1


array([-9. ,  1. ,  1.1, 45. ])

In [14]:
#Sorting/Unique Values
arr1

array([-9. ,  1. ,  1.1, 45. ])

In [16]:
arr1.sort()
arr1

array([-9. ,  1. ,  1.1, 45. ])

In [17]:
#get unique values in sorted order
tickers=np.array(['Tech','Tech','Cons','Energy','XOM','XOM'])
np.unique(tickers)

array(['Cons', 'Energy', 'Tech', 'XOM'], dtype='<U6')