In [13]:
#Integer Indexing
# Boolean Indexing

#initialize
import numpy as np

list1 = [1,1.1,-9,76]
arr1 = np.array(list1)

list1 = [[8,98,76,-45],[0,87,34,21]]
arr2 = np.array(list1)

In [3]:
#Integer Indexing
print(arr1[0])
print(arr1[1:3])
print(arr1[-2: ])

8
[98 76]
[ 76 -45]


In [7]:
# 2-D array indexing
arr2

array([  8,  98,  76, -45])

In [14]:
arr2[0]

array([  8,  98,  76, -45])

In [16]:
arr2[0][1]

np.int64(98)

In [17]:
arr2[0,]

array([  8,  98,  76, -45])

In [18]:
arr2[0, :3]

array([ 8, 98, 76])

In [19]:
arr2[:, :3]

array([[ 8, 98, 76],
       [ 0, 87, 34]])

In [20]:
arr2[:, [1,3,-1]]

array([[ 98, -45, -45],
       [ 87,  21,  21]])

In [21]:
#Boolean Indexing

mask = arr1>0
mask

array([ True,  True, False,  True])

In [22]:
arr1[mask]

array([ 1. ,  1.1, 76. ])

In [23]:
arr2[[True, False], :2] # this will represent row1 and upto 2nd column

array([[ 8, 98]])

In [24]:
arr2

array([[  8,  98,  76, -45],
       [  0,  87,  34,  21]])