In [2]:
import numpy as np
x = np.array([[1, 2, 3], [4,5,6]])
x

array([[1, 2, 3],
       [4, 5, 6]])

In [5]:
y = np.array([[6, 23], [-1,7],[8, 9]])
y

array([[ 6, 23],
       [-1,  7],
       [ 8,  9]])

In [6]:
#multiply matrices
x.dot(y)

array([[ 28,  64],
       [ 67, 181]])

In [7]:
np.dot(x,y)

array([[ 28,  64],
       [ 67, 181]])

In [8]:
#multiply shorthand
x @y

array([[ 28,  64],
       [ 67, 181]])

In [9]:
# Transpose
x.T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [10]:
#inverse
np.linalg.inv(x@y)

array([[ 0.23205128, -0.08205128],
       [-0.08589744,  0.03589744]])