In [3]:
# Function that performs elementwise operations on data in arrays
import numpy as np
# many ufuncs operate on a single array
arr = np.array([1,4,9,16])
np.sqrt(arr)

array([1., 2., 3., 4.])

In [4]:
np.log(arr)

array([0.        , 1.38629436, 2.19722458, 2.77258872])

In [5]:
# some ufuncs operate on multiple array(Binary Universal Functions)
arr1 = np.array([1,-9, 3,5])
arr2 = np.array([2,11,4,32])
np.maximum(arr1, arr2)
np.minimum(arr1, arr2)

array([ 1, -9,  3,  5])