In [1]:
#Numpy - "Numerical Python" Foundation for pandas and high performance scientific computing/data analysis

#1. Numpy Arrays
#2. Basic Operations
#3 Indexing
#4 Universal Functions
#5 Array methods for data analysis
#6 Linear Algebra

In [4]:
import numpy as np
#use np.some_numpy_method to use numpy
np.abs(-6)

np.int64(6)

In [6]:
#import only as absolute value function from numpy
from numpy import array, dot, sign

#import all functions from numpy
from numpy import *


In [17]:
#Numpy Arrays
#1D Array
list1 =[1,1.1,-8,4.3]
arr1 = np.array(list1)
arr1

array([ 1. ,  1.1, -8. ,  4.3])

In [11]:
#2D Array
list2 = [[1,1.1,-3,34], [-0.4, 10, 23, 87]]  #both the sub-list should be of same size
arr2 = np.array(list2)
arr2

array([[ 1. ,  1.1, -3. , 34. ],
       [-0.4, 10. , 23. , 87. ]])

In [13]:
arr1.shape

(4,)

In [14]:
arr2.shape

(2, 4)

In [20]:
#Basic Operations
#Operations between equal-size arrays or arrays and scalars operate element-wise
#No loops needed
#numpy makes array - scalar operations easier
arr1-5  #cannot be implemented directly on list it should be numpy array

array([ -4. ,  -3.9, -13. ,  -0.7])

In [21]:
#if we want to do using list: clunky loop
new_list=[]
for x in list1:
    new_list.append(x)
print(new_list)

[1, 1.1, -8, 4.3]


In [23]:
#numpy makes array to array operations easier
arr1*arr1

array([ 1.  ,  1.21, 64.  , 18.49])

In [25]:
#numpy makes array to scalar boolean logic easier
arr1 > 0

array([ True,  True, False,  True])

In [27]:
#using lists : very clunky loop
is_pos =[]
for x in list1:
    is_pos.append(x > 0)

is_pos

[True, True, False, True]

In [28]:
arr1>0

array([ True,  True, False,  True])

In [29]:
#numpy makes array to array boolean logic easier
arr1 = np.array([1,89,0.9,34])
arr2 = np.array([1,2,3,4])
arr1> arr2

array([False,  True, False,  True])

In [30]:
#numpy makes logical operations on boolean array easier
bool1 = (arr1>0)
bool1

array([ True,  True,  True,  True])

In [32]:
bool2 = (arr1>1)
bool2

array([False,  True, False,  True])

In [33]:
bool1 & bool2

array([False,  True, False,  True])

In [34]:
bool1 | bool2

array([ True,  True,  True,  True])